# Generated by Django 5.2.4 on 2025-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_criado_em_avaliacao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
