# Generated by Django 5.2.4 on 2025-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_filme_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
