# Generated by Django 5.2.4 on 2025-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_genero_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
