# Generated by Django 5.2.4 on 2025-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_trailer_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacao',
            name='codigo',
        ),
        migrations.AddField(
            model_name='classificacao',
            name='idade_minima',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classificacao',
            name='nome',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
