# Generated by Django 5.2.4 on 2025-07-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_classificacao_codigo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='nome',
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='idade_minima',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='criado_em',
        ),
    ]
